# Generated by Django 2.0.4 on 2018-04-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(help_text='A college he stydied', max_length=30, verbose_name='College name'),
        ),
        migrations.AlterField(
            model_name='match',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Arena'),
        ),
    ]
