# Generated by Django 2.0.4 on 2018-04-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20180430_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team2',
            new_name='Away Team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='Home Team',
        ),
    ]
