# Generated by Django 2.0.4 on 2018-04-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20180430_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Away Team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Home Team',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='statistic.Team', verbose_name='Home Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='statistic.Team', verbose_name='Away Team'),
            preserve_default=False,
        ),
    ]
