# Generated by Django 2.0.4 on 2018-05-07 12:20

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_auto_20180502_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 12, 20, 45, 624453, tzinfo=utc), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
