# Generated by Django 2.0.4 on 2018-05-07 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_auto_20180507_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='teams_logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 23, 6, 42, 647069, tzinfo=utc), verbose_name='Date and Time'),
        ),
    ]
