# Generated by Django 2.0.4 on 2018-05-09 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_auto_20180507_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 22, 7, 1, 456199, tzinfo=utc), verbose_name='Date and Time'),
        ),
    ]
