# Generated by Django 2.0.4 on 2018-05-10 01:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_auto_20180509_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('points', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)])),
                ('rebounds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('assists', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('steals', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('blocks', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 1, 3, 48, 435722, tzinfo=utc), verbose_name='Date and Time'),
        ),
        migrations.AddField(
            model_name='stat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Match'),
        ),
        migrations.AddField(
            model_name='stat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Player'),
        ),
    ]
