# Generated by Django 2.0.4 on 2018-05-10 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_auto_20180510_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'permissions': (('statistic.can_moderate', 'Moderate data in app statistic'),), 'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 10, 12, 33, 652336, tzinfo=utc), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
