# Generated by Django 2.0.4 on 2018-05-14 22:19

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0013_auto_20180513_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 22, 19, 6, 169080, tzinfo=utc), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(170)], verbose_name='Home Scores'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(default=51, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(170)], verbose_name='Away Scores'),
        ),
    ]
