# Generated by Django 2.0.4 on 2018-05-22 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20180514_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='16:35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arena',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(help_text='A college he stydied', max_length=30, unique=True, verbose_name='College name'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(170)], verbose_name='Home Scores'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(verbose_name='Away Scores'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='country',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
