# Generated by Django 2.0.4 on 2018-05-22 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0015_auto_20180522_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(170)], verbose_name='Away Scores'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='statistic.Team', verbose_name='Home Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='statistic.Team', verbose_name='Away Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='Free agent', on_delete=django.db.models.deletion.SET_DEFAULT, to='statistic.Team'),
        ),
    ]
