# Generated by Django 2.0.4 on 2018-05-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0016_auto_20180522_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Arena'),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statistic.College'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Nationality'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Arena'),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.Conference'),
        ),
    ]
