# Generated by Django 2.0.4 on 2018-05-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0017_auto_20180522_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='statistic.Team', unique=True, verbose_name='Home Team'),
        ),
    ]
