# Generated by Django 2.0.4 on 2018-05-23 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0019_auto_20180523_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='blocks',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='points',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='rebounds',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='steals',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
