# Generated by Django 2.0.4 on 2018-05-23 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0020_auto_20180523_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='number_matches',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(82)]),
        ),
        migrations.AddField(
            model_name='stat',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='statistic.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='players_profiles', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='rebounds',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
