# Generated by Django 2.0.4 on 2018-05-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0023_auto_20180523_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='statistic.Coach', unique=True),
        ),
    ]
