# Generated by Django 2.0.4 on 2018-05-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0024_auto_20180523_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='coach',
        ),
    ]
