# Generated by Django 2.0.4 on 2018-05-09 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistic', '0008_auto_20180509_2207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Player')),
                ('favorite_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
