# Generated by Django 2.0.4 on 2018-05-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_auto_20180510_1323'),
        ('users', '0003_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Player')),
                ('favorite_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_player',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_team',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
