# Generated by Django 2.0.4 on 2018-05-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180510_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
    ]
