# Generated by Django 2.0.4 on 2018-05-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180513_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_player',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
